version: '3'

services:
  app:
    build: .
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@db/database}
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-database}
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - PGPORT=${DATABASE_PORT:-5432}
    ports:
      - '${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
