name: Students API Pipeline

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  deploy:
    name: Deploy container to Heroku
    runs-on: ubuntu-latest
    needs: setup
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        run: heroku container:login
      - name: Build and push container
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release container
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
